name: .NET

on:
  push:
    tags: [ "v*" ]
    branches: [ "master" ]

env: 
  NUGET_API_KEY: '{{ secrets.NUGET_API_KEY }}'
  BuildConfiguration: 'Release'
  PROJECT_PATH: 'FormToastHelper\src\FormHelper'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Set Version
      run: echo "Version=1.0.0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Display Api Key
      run: echo "Version is $env:NUGET_API_KEY"

    - name: Build Script
      run: |
        . .\build.ps1
        CIBuild
