name: .NET

on:
  push:
    tags: [ "v*" ]
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Set Api Key
      run: echo "NUGET_API_KEY=${{ secrets.NUGET_API_KEY }}" >> "$GITHUB_ENV"

    - name: Set Version
      run: echo "Version=1.0.0" >> "$GITHUB_ENV"

    - name: Display Api Key
      run: echo "Version is $env:NUGET_API_KEY"

    - name: Build Script
      run: |
        . .\build.ps1
        CIBuild
